basePath: /api
definitions:
  domain.ConfirmEmailVerificationRequest:
    properties:
      token:
        type: string
    required:
    - token
    type: object
  domain.ConfirmPasswordResetRequest:
    properties:
      new_password:
        type: string
      token:
        type: string
    required:
    - new_password
    - token
    type: object
  domain.Login:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  domain.LoginResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      session_id:
        type: string
      user_id:
        type: string
      user_type:
        type: string
    type: object
  domain.RefreshRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  domain.RequestPasswordResetRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  domain.Role:
    properties:
      id:
        type: string
      roleName:
        type: string
    type: object
  domain.SignupRequest:
    properties:
      admin_email:
        type: string
      admin_first_name:
        type: string
      admin_last_name:
        type: string
      admin_password:
        type: string
      clinic_name:
        type: string
      registration_no:
        type: string
    required:
    - admin_email
    - admin_first_name
    - admin_last_name
    - admin_password
    - clinic_name
    - registration_no
    type: object
  domain.User:
    properties:
      clinicID:
        type: string
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      password:
        $ref: '#/definitions/valueobjects.Password'
      roleID:
        type: string
      updatedAt:
        type: string
    type: object
  domain.VisitStatus:
    enum:
    - scheduled
    - waiting
    - examining
    - completed
    - cancelled
    type: string
    x-enum-varnames:
    - Scheduled
    - Waiting
    - Examining
    - Completed
    - Cancelled
  dto.AddStockReq:
    properties:
      notes:
        type: string
      quantity:
        minimum: 1
        type: integer
    required:
    - quantity
    type: object
  dto.ClinicRequest:
    properties:
      address:
        type: string
      clinic_name:
        type: string
      email:
        type: string
      phone:
        type: string
      registration_no:
        type: string
      report_footer:
        type: string
      tagline:
        type: string
    required:
    - clinic_name
    - registration_no
    type: object
  dto.ClinicResponse:
    properties:
      address:
        type: string
      clinic_name:
        type: string
      email:
        type: string
      id:
        type: string
      phone:
        type: string
      registration_no:
        type: string
